# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arm_control_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(553, 440)
        self.btn_pan_left = QtWidgets.QPushButton(Form)
        self.btn_pan_left.setGeometry(QtCore.QRect(70, 50, 121, 31))
        self.btn_pan_left.setObjectName("btn_pan_left")
        self.btn_pan_right = QtWidgets.QPushButton(Form)
        self.btn_pan_right.setGeometry(QtCore.QRect(350, 50, 121, 31))
        self.btn_pan_right.setObjectName("btn_pan_right")
        self.btn_lift_up = QtWidgets.QPushButton(Form)
        self.btn_lift_up.setGeometry(QtCore.QRect(70, 100, 121, 31))
        self.btn_lift_up.setObjectName("btn_lift_up")
        self.btn_lift_down = QtWidgets.QPushButton(Form)
        self.btn_lift_down.setGeometry(QtCore.QRect(350, 100, 121, 31))
        self.btn_lift_down.setObjectName("btn_lift_down")
        self.btn_elbow_ext = QtWidgets.QPushButton(Form)
        self.btn_elbow_ext.setGeometry(QtCore.QRect(70, 150, 121, 31))
        self.btn_elbow_ext.setObjectName("btn_elbow_ext")
        self.btn_elbow_ret = QtWidgets.QPushButton(Form)
        self.btn_elbow_ret.setGeometry(QtCore.QRect(350, 150, 121, 31))
        self.btn_elbow_ret.setObjectName("btn_elbow_ret")
        self.btn_wrist1_pos = QtWidgets.QPushButton(Form)
        self.btn_wrist1_pos.setGeometry(QtCore.QRect(70, 200, 121, 31))
        self.btn_wrist1_pos.setObjectName("btn_wrist1_pos")
        self.btn_wrist1_neg = QtWidgets.QPushButton(Form)
        self.btn_wrist1_neg.setGeometry(QtCore.QRect(350, 200, 121, 31))
        self.btn_wrist1_neg.setObjectName("btn_wrist1_neg")
        self.btn_wrist2_pos = QtWidgets.QPushButton(Form)
        self.btn_wrist2_pos.setGeometry(QtCore.QRect(70, 250, 121, 31))
        self.btn_wrist2_pos.setObjectName("btn_wrist2_pos")
        self.btn_wrist2_neg = QtWidgets.QPushButton(Form)
        self.btn_wrist2_neg.setGeometry(QtCore.QRect(350, 250, 121, 31))
        self.btn_wrist2_neg.setObjectName("btn_wrist2_neg")
        self.btn_wrist3_pos = QtWidgets.QPushButton(Form)
        self.btn_wrist3_pos.setGeometry(QtCore.QRect(70, 300, 121, 31))
        self.btn_wrist3_pos.setObjectName("btn_wrist3_pos")
        self.btn_wrist3_neg = QtWidgets.QPushButton(Form)
        self.btn_wrist3_neg.setGeometry(QtCore.QRect(350, 300, 121, 31))
        self.btn_wrist3_neg.setObjectName("btn_wrist3_neg")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_pan_left.setText(_translate("Form", "pan_left"))
        self.btn_pan_right.setText(_translate("Form", "pan_right"))
        self.btn_lift_up.setText(_translate("Form", "lift_up"))
        self.btn_lift_down.setText(_translate("Form", "lift_down"))
        self.btn_elbow_ext.setText(_translate("Form", "elbow_ext"))
        self.btn_elbow_ret.setText(_translate("Form", "elbow_ret"))
        self.btn_wrist1_pos.setText(_translate("Form", "wrist1_pos"))
        self.btn_wrist1_neg.setText(_translate("Form", "wrist1_neg"))
        self.btn_wrist2_pos.setText(_translate("Form", "wrist2_pos"))
        self.btn_wrist2_neg.setText(_translate("Form", "wrist2_neg"))
        self.btn_wrist3_pos.setText(_translate("Form", "_wrist_pos"))
        self.btn_wrist3_neg.setText(_translate("Form", "wrist3_neg"))
